---
title: '"COMPSCIX 415.2 Homework 1"'
author: "Chisun  Fan"
date: "February 2, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




My Github repository for my assignments can be found at this URL: [https://github.com/chisunfan/compscix-415-2-assignments/tree/master/Lab1] (https://github.com/chisunfan/compscix-415-2-assignments/tree/master/Lab1) 

Answer to question 1: 
There are 23,018 observations and 10 variables in WorldCities data set.  code, name, latitude, and country are some of the variable names.

## R Markdown



```{r load_packages, warning=FALSE, message=FALSE}
library(mdsr)
library(tidyverse)
data("WorldCities")
glimpse(WorldCities)
WorldCities <- head(WorldCities,200) # 200 rows
country_col <- WorldCities$country
unique(country_col)
```
Question 2 output

```{r}
region_col <- WorldCities$region
unique(region_col)
```
Question 3 output

```{r}
WorldCities %>% select(country) %>% unique()

```
question 4 output
```{r}
WorldCities %>% ggplot(aes(x = population)) +
  geom_histogram() +
  xlab('Region Population') +
  ylab('Total count') +
  theme_bw(base_size = 15)
```

 